export const SET_NICKNAME = 'SET_NICKNAME';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const DISCONNECT_USER = 'DISCONNECT_USER';
export const CREATE_USER_SOCKET = 'CREATE_USER_SOCKET';
